// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: api/helloworld.proto

package api

import (
	context "context"
	websocket "github.com/neo532/gofr/transport/websocket"
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

func _registerGreeterWebSocket(s *websocket.Server, svr Greeter) {

	s.Handle("/helloworld.Greeter/SayHello", func(ctx context.Context, conn *websocket.Conn) error {
		_, data, err := conn.ReadMessage()
		if err != nil {
			return err
		}
		req := &HelloRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return err
		}
		resp, err := svr.SayHello(ctx, req)
		if err != nil {
			return err
		}
		data, err = proto.Marshal(resp)
		if err != nil {
			return err
		}
		return conn.WriteMessage(websocket.BinaryMessage, data)
	})

	s.Handle("/helloworld.Greeter/Hello", func(ctx context.Context, conn *websocket.Conn) error {
		_, data, err := conn.ReadMessage()
		if err != nil {
			return err
		}
		req := &HelloRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return err
		}
		resp, err := svr.Hello(ctx, req)
		if err != nil {
			return err
		}
		data, err = proto.Marshal(resp)
		if err != nil {
			return err
		}
		return conn.WriteMessage(websocket.BinaryMessage, data)
	})

}

// RegisterWebsocketServer registers each service method as a WebSocket handler.
// It matches each svr to its service descriptor by the concrete type name.
// Panics if any defined service is left unimplemented.
func RegisterWebsocketServer(s *websocket.Server, svrs ...any) {
	matched := map[string]bool{
		"Greeter": false,
	}
	for _, svr := range svrs {
		t := reflect.TypeOf(svr)
		if t.Kind() == reflect.Ptr {
			t = t.Elem()
		}
		typeName := t.Name()
		switch typeName {
		case "Greeter":
			matched["Greeter"] = true
			_registerGreeterWebSocket(s, svr.(Greeter))
		default:
			fallbackRegisterWebSocket(s, svr, matched)
		}
	}
	for svc, ok := range matched {
		if !ok {
			panic("gofr: websocket service \"" + svc + "\" has no implementation")
		}
	}
}

func fallbackRegisterWebSocket(s *websocket.Server, svr any, matched map[string]bool) {
	switch v := svr.(type) {
	case Greeter:
		matched["Greeter"] = true
		_registerGreeterWebSocket(s, v)
	}
}
