// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: api/helloworld.proto

package api

import (
	context "context"
	grpc "github.com/neo532/gofr/transport/grpc"
	reflect "reflect"
)

func _registerGreeterGRPC(s *grpc.Server, svr Greeter) {
	grpc.RegisterServiceWith(s, "helloworld.Greeter", svr, []struct {
		Name    string
		NewReq  func() any
		Handler grpc.UnaryHandler
	}{
		{Name: "SayHello", NewReq: func() any { return &HelloRequest{} }, Handler: func(ctx context.Context, req any) (any, error) {
			return svr.SayHello(ctx, req.(*HelloRequest))
		}},
		{Name: "Hello", NewReq: func() any { return &HelloRequest{} }, Handler: func(ctx context.Context, req any) (any, error) {
			return svr.Hello(ctx, req.(*HelloRequest))
		}},
	})
}

// RegisterGRPCServer registers all services to the gRPC server.
// It matches each svr to its service descriptor by the concrete type name.
// Panics if any defined service is left unimplemented.
func RegisterGRPCServer(s *grpc.Server, svrs ...any) {
	matched := map[string]bool{
		"Greeter": false,
	}
	for _, svr := range svrs {
		t := reflect.TypeOf(svr)
		if t.Kind() == reflect.Ptr {
			t = t.Elem()
		}
		typeName := t.Name()
		switch typeName {
		case "Greeter":
			matched["Greeter"] = true
			_registerGreeterGRPC(s, svr.(Greeter))
		default:
			fallbackRegisterGRPC(s, svr, matched)
		}
	}
	for svc, ok := range matched {
		if !ok {
			panic("gofr: gRPC service \"" + svc + "\" has no implementation")
		}
	}
}

func fallbackRegisterGRPC(s *grpc.Server, svr any, matched map[string]bool) {
	switch v := svr.(type) {
	case Greeter:
		matched["Greeter"] = true
		_registerGreeterGRPC(s, v)
	}
}
