// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: example/helloworld/api/helloworld.proto

package api

import (
	http "github.com/neo532/gofr/transport/http"
)

func _registerGreeterHTTP(s *http.Server, svr GreeterServer) {
	http.RegisterUnary(s, "POST", "/api/v1/greeter", svr.SayHello, func(ctx http.Context, req *HelloRequest) error {
		return ctx.Bind(req)
	})
	http.RegisterUnary(s, "GET", "/api/v1/hello/:name", svr.Hello, func(ctx http.Context, req *HelloRequest) error {
		if v := ctx.PathValue("name"); v != "" {
			req.Name = v
		}
		return nil
	})
}

// RegisterHTTPServer registers all services to the HTTP server.
func RegisterHTTPServer(s *http.Server, svrs ...any) {
	for _, svr := range svrs {
		switch v := svr.(type) {
		case GreeterServer:
			_registerGreeterHTTP(s, v)
		}
	}
}
