// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: example/helloworld/api/helloworld.proto

package api

import (
	"context"

	"github.com/neo532/gofr/transport/rpcx"
	"google.golang.org/protobuf/proto"
)

// GreeterRPCXWrapper adapts GreeterServer to rpcx's expected method signature.
type GreeterRPCXWrapper struct {
	inner GreeterServer
}

func (w *GreeterRPCXWrapper) SayHello(ctx context.Context, args *HelloRequest, reply *HelloReply) error {
	result, err := w.inner.SayHello(ctx, args)
	if err != nil {
		return err
	}
	proto.Merge(reply, result)
	return nil
}

func (w *GreeterRPCXWrapper) Hello(ctx context.Context, args *HelloRequest, reply *HelloReply) error {
	result, err := w.inner.Hello(ctx, args)
	if err != nil {
		return err
	}
	proto.Merge(reply, result)
	return nil
}

func _registerGreeterRPCX(s *rpcx.Server, svr GreeterServer) {
	rpcx.RegisterServiceWith(s, "helloworld.Greeter", &GreeterRPCXWrapper{inner: svr})
}

// RegisterRPCXServer registers all services to the rpcx server.
func RegisterRPCXServer(s *rpcx.Server, svrs ...any) {
	for _, svr := range svrs {
		switch v := svr.(type) {
		case GreeterServer:
			_registerGreeterRPCX(s, v)
		}
	}
}
