// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: example/helloworld/api/helloworld.proto

package api

import (
	httprouter "github.com/julienschmidt/httprouter"
	http "github.com/neo532/gofr/transport/http"
	reflect "reflect"
)

func _registerGreeterHTTP(s *http.Server, svr Greeter) {
	http.HandleUnary(s, "POST", "/api/v1/greeter", svr.SayHello, nil)
	http.HandleUnary(s, "GET", "/api/v1/hello/:name", svr.Hello, func(ps httprouter.Params, req *HelloRequest) error {
		req.Name = ps.ByName("name")
		return nil
	})
}

// RegisterHTTPServer registers all services to the HTTP server.
// It matches each svr to its service descriptor by the concrete type name.
// Panics if any defined service is left unimplemented.
func RegisterHTTPServer(s *http.Server, svrs ...any) {
	matched := map[string]bool{
		"Greeter": false,
	}
	for _, svr := range svrs {
		t := reflect.TypeOf(svr)
		if t.Kind() == reflect.Ptr {
			t = t.Elem()
		}
		typeName := t.Name()
		switch typeName {
		case "Greeter":
			matched["Greeter"] = true
			_registerGreeterHTTP(s, svr.(Greeter))
		default:
			fallbackRegisterHTTPServer(s, svr, matched)
		}
	}
	for svc, ok := range matched {
		if !ok {
			panic("gofr: HTTP service \"" + svc + "\" has no implementation")
		}
	}
}

// fallbackRegisterHTTPServer tries interface-based matching.
func fallbackRegisterHTTPServer(s *http.Server, svr any, matched map[string]bool) {
	switch v := svr.(type) {
	case Greeter:
		matched["Greeter"] = true
		_registerGreeterHTTP(s, v)
	}
}

// HTTPRoutes maps each gRPC full method (Service/Method) to its HTTP binding,
// so a gRPC/rpcx call can be replayed as a curl against the HTTP endpoint.
var HTTPRoutes = map[string]http.Route{
	"helloworld.Greeter/SayHello": {Service: "helloworld.Greeter", Method: "SayHello", HTTPMethod: "POST", Path: "/api/v1/greeter"},
	"helloworld.Greeter/Hello":    {Service: "helloworld.Greeter", Method: "Hello", HTTPMethod: "GET", Path: "/api/v1/hello/{name}"},
}

func init() { http.RegisterRoutes(HTTPRoutes) }

// HTTPPathParams returns each method's path-param values as strings so a
// gRPC/rpcx call can be replayed as an HTTP curl without reflection.
var HTTPPathParams = map[string]http.PathParamFunc{
	"helloworld.Greeter/Hello": func(m any) map[string]string {
		x := m.(*HelloRequest)
		return map[string]string{
			"name": x.GetName(),
		}
	},
}

func init() { http.RegisterPathParams(HTTPPathParams) }
