// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: example/helloworld/api/helloworld.proto

package api

import (
	context "context"
	transport "github.com/neo532/gofr/transport"
)

// GreeterServer is the server API for helloworld.Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	Hello(context.Context, *HelloRequest) (*HelloReply, error)
}

// GreeterServiceDesc is the protocol-agnostic service descriptor.
var GreeterServiceDesc = &transport.ServiceDesc{
	Name: "helloworld.Greeter",
	Methods: []transport.MethodDesc{
		{
			Name:       "SayHello",
			NewRequest: func() interface{} { return &HelloRequest{} },
			HTTPMethod: "POST",
			HTTPPath:   "/api/v1/greeter",
		},
		{
			Name:       "Hello",
			NewRequest: func() interface{} { return &HelloRequest{} },
			HTTPMethod: "GET",
			HTTPPath:   "/api/v1/hello/{name}",
		},
	},
}
