// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: api/helloworld.proto

package api

import (
	context "context"
)

// Greeter is the server API for helloworld.Greeter service.
type Greeter interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	Hello(context.Context, *HelloRequest) (*HelloReply, error)
}
