// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: api/helloworld.proto

package api

import (
	http "github.com/neo532/gofr/transport/http"
	reflect "reflect"
)

func _registerGreeterHTTP(s *http.Server, svr Greeter) {
	http.RegisterUnary(s, "POST", "/api/v1/greeter", svr.SayHello, func(ctx http.Context, req *HelloRequest) error {
		if err := ctx.Bind(req); err != nil {
			return err
		}
		return nil
	})
	http.RegisterUnary(s, "GET", "/api/v1/hello/:name", svr.Hello, func(ctx http.Context, req *HelloRequest) error {
		if err := ctx.Bind(req); err != nil {
			return err
		}
		req.Name = ctx.PathValue("name")
		return nil
	})
}

// RegisterHTTPServer registers all services to the HTTP server.
// It matches each svr to its service descriptor by the concrete type name.
// Panics if any defined service is left unimplemented.
func RegisterHTTPServer(s *http.Server, svrs ...any) {
	matched := map[string]bool{
		"Greeter": false,
	}
	for _, svr := range svrs {
		t := reflect.TypeOf(svr)
		if t.Kind() == reflect.Ptr {
			t = t.Elem()
		}
		typeName := t.Name()
		switch typeName {
		case "Greeter":
			matched["Greeter"] = true
			_registerGreeterHTTP(s, svr.(Greeter))
		default:
			fallbackRegisterHTTPServer(s, svr, matched)
		}
	}
	for svc, ok := range matched {
		if !ok {
			panic("gofr: HTTP service \"" + svc + "\" has no implementation")
		}
	}
}

// fallbackRegisterHTTPServer tries interface-based matching.
func fallbackRegisterHTTPServer(s *http.Server, svr any, matched map[string]bool) {
	switch v := svr.(type) {
	case Greeter:
		matched["Greeter"] = true
		_registerGreeterHTTP(s, v)
	}
}
