// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: example/helloworld/api/helloworld.proto

package api

import (
	context "context"
	rpcx "github.com/neo532/gofr/transport/rpcx"
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

// GreeterRPCXWrapper adapts Greeter to rpcx's expected method signature.
type GreeterRPCXWrapper struct {
	inner Greeter
}

func (w *GreeterRPCXWrapper) SayHello(ctx context.Context, args *HelloRequest, reply *HelloReply) error {
	result, err := w.inner.SayHello(ctx, args)
	if err != nil {
		return err
	}
	proto.Merge(reply, result)
	return nil
}

func (w *GreeterRPCXWrapper) Hello(ctx context.Context, args *HelloRequest, reply *HelloReply) error {
	result, err := w.inner.Hello(ctx, args)
	if err != nil {
		return err
	}
	proto.Merge(reply, result)
	return nil
}

func _registerGreeterRPCX(s *rpcx.Server, svr Greeter) {
	rpcx.RegisterServiceWith(s, "helloworld.Greeter", &GreeterRPCXWrapper{inner: svr})
}

// RegisterRPCXServer registers all services to the rpcx server.
// It matches each svr to its service descriptor by the concrete type name.
// Panics if any defined service is left unimplemented.
func RegisterRPCXServer(s *rpcx.Server, svrs ...any) {
	matched := map[string]bool{
		"Greeter": false,
	}
	for _, svr := range svrs {
		t := reflect.TypeOf(svr)
		if t.Kind() == reflect.Ptr {
			t = t.Elem()
		}
		typeName := t.Name()
		switch typeName {
		case "Greeter":
			matched["Greeter"] = true
			_registerGreeterRPCX(s, svr.(Greeter))
		default:
			fallbackRegisterRPCX(s, svr, matched)
		}
	}
	for svc, ok := range matched {
		if !ok {
			panic("gofr: rpcx service \"" + svc + "\" has no implementation")
		}
	}
}

func fallbackRegisterRPCX(s *rpcx.Server, svr any, matched map[string]bool) {
	switch v := svr.(type) {
	case Greeter:
		matched["Greeter"] = true
		_registerGreeterRPCX(s, v)
	}
}
