package main

import (
	"fmt"
	"path"
	"strconv"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type protocols struct {
	HTTP bool
	GRPC bool
	RPCX bool
	WS   bool
}

func parseProtocols(param string) protocols {
	p := protocols{HTTP: true, GRPC: true, RPCX: true, WS: true}
	if param == "" || !strings.Contains(param, "protocols=") {
		return p
	}
	idx := strings.Index(param, "protocols=")
	rest := param[idx+len("protocols="):]
	var names []string
	for _, part := range strings.Split(rest, ",") {
		if strings.Contains(part, "=") {
			break
		}
		names = append(names, strings.TrimSpace(part))
	}
	enabled := make(map[string]bool)
	for _, name := range names {
		enabled[name] = true
	}
	p.HTTP = enabled["http"]
	p.GRPC = enabled["grpc"]
	p.RPCX = enabled["rpcx"]
	p.WS = enabled["ws"] || enabled["websocket"]
	return p
}

func generateFile(gen *protogen.Plugin, file *protogen.File, protos protocols) error {
	if len(file.Services) == 0 {
		return nil
	}

	pkg := string(file.GoPackageName)

	// Build shared service descriptors (used by both base client and per-protocol files).

	// ─── Base client file (_client.pb.go) ───
	baseFilename := file.GeneratedFilenamePrefix + "_client.pb.go"
	bg := gen.NewGeneratedFile(baseFilename, file.GoImportPath)
	bg.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
	bg.P("// source: ", file.Desc.Path())
	bg.P()
	bg.P("package ", file.GoPackageName)
	bg.P()

	bg.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: "context",
		GoName:       "Context",
	})
	// Register imports for all request/reply types
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			bg.QualifiedGoIdent(method.Input.GoIdent)
			bg.QualifiedGoIdent(method.Output.GoIdent)
		}
	}

	buildServices := func(unusedIdent func(protogen.GoIdent) string) []*serviceDesc {
		var services []*serviceDesc
		for _, svc := range file.Services {
			sd := &serviceDesc{
				ServiceType: svc.GoName,
				ServiceName: string(svc.Desc.FullName()),
			}
			for _, method := range svc.Methods {
				md := methodDesc{
					Name:      method.GoName,
					FieldName: fieldName(method.GoName),
					Request:   unusedIdent(method.Input.GoIdent),
					Reply:     unusedIdent(method.Output.GoIdent),
				}
				sd.Methods = append(sd.Methods, md)
			}
			services = append(services, sd)
		}
		return services
	}

	output := generateClient(pkg, buildServices(func(id protogen.GoIdent) string {
		return bg.QualifiedGoIdent(id)
	}))
	for _, line := range splitLines(output) {
		bg.P(line)
	}

	// ─── Per-protocol files ───

	if protos.HTTP {
		filename := file.GeneratedFilenamePrefix + "_client_http.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})
		reqs, err := enrichHTTPServices(file, services)
		if err != nil {
			return err
		}

		imports := httpImportNames{
			Context:   qualifiedPackage(g, "context", "Context"),
			Fmt:       qualifiedPackage(g, "fmt", "Errorf"),
			IO:        qualifiedPackage(g, "io", "ReadAll"),
			HTTP:      qualifiedPackage(g, "net/http", "Client"),
			ProtoJSON: qualifiedPackage(g, "google.golang.org/protobuf/encoding/protojson", "MarshalOptions"),
			Strings:   qualifiedPackage(g, "strings", "TrimSpace"),
		}
		if reqs.Bytes {
			imports.Bytes = qualifiedPackage(g, "bytes", "NewReader")
		}
		if reqs.URL {
			imports.URL = qualifiedPackage(g, "net/url", "Parse")
		}
		if reqs.Strconv {
			imports.Strconv = qualifiedPackage(g, "strconv", "Itoa")
		}
		for _, svc := range services {
			for i := range svc.Methods {
				svc.Methods[i].HTTPCode = replaceHTTPImports(svc.Methods[i].HTTPCode, imports)
			}
		}

		data := &fileDesc{
			PackageName:  pkg,
			HelperPrefix: helperPrefix(file.GeneratedFilenamePrefix),
			Services:     services,
			Context:      imports.Context,
			Bytes:        imports.Bytes,
			Fmt:          imports.Fmt,
			IO:           imports.IO,
			HTTP:         imports.HTTP,
			URL:          imports.URL,
			ProtoJSON:    imports.ProtoJSON,
			Strconv:      imports.Strconv,
			Strings:      imports.Strings,
		}
		output := generateHTTPClient(data)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.GRPC {
		filename := file.GeneratedFilenamePrefix + "_client_grpc.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/grpc", GoName: "ClientConnInterface"})

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateGRPCClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.RPCX {
		filename := file.GeneratedFilenamePrefix + "_client_rpcx.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/smallnest/rpcx/client", GoName: "XClient"})

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateRPCXClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.WS {
		filename := file.GeneratedFilenamePrefix + "_client_ws.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/gorilla/websocket", GoName: "Conn"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "net/http", GoName: "Header"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/protobuf/proto", GoName: "Marshal"})

		// WSDialer lets a caller inject any dialer whose signature matches
		// *websocket.Dialer — for example websocket.NewClient()
		// (github.com/neo532/gofr/transport/websocket), which wires middleware
		// and retry onto the dial. It is self-contained so generated code does
		// not import gofr.
		g.P("// WSDialer dials a websocket endpoint. *websocket.Dialer satisfies it.")
		g.P("type WSDialer interface {")
		g.P("\tDialContext(ctx context.Context, urlStr string, requestHeader http.Header) (*websocket.Conn, *http.Response, error)")
		g.P("}")

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateWSClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	// ─── Client set dispatcher file (_client_set.pb.go) ───
	// A single switch dispatcher per service, keyed by protocol kind string,
	// that routes (kind, handle, baseURL) to the matching per-protocol
	// constructor. The kind strings mirror transport.Kind values so callers
	// can pass them unmodified; generated code does not import gofr.
	filename := file.GeneratedFilenamePrefix + "_client_set.pb.go"
	cs := gen.NewGeneratedFile(filename, file.GoImportPath)
	cs.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
	cs.P("// source: ", file.Desc.Path())
	cs.P()
	cs.P("package ", file.GoPackageName)
	cs.P()

	if protos.GRPC {
		cs.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/grpc", GoName: "ClientConnInterface"})
	}
	if protos.RPCX {
		cs.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/smallnest/rpcx/client", GoName: "XClient"})
	}
	if protos.HTTP {
		cs.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "net/http", GoName: "Client"})
	}

	setServices := buildServices(func(id protogen.GoIdent) string {
		return string(id.GoName)
	})
	setOutput := generateClientSet(&fileDesc{
		PackageName: pkg,
		Services:    setServices,
		HasHTTP:     protos.HTTP,
		HasGRPC:     protos.GRPC,
		HasRPCX:     protos.RPCX,
		HasWS:       protos.WS,
	})
	for _, line := range splitLines(setOutput) {
		cs.P(line)
	}
	return nil
}

func qualifiedPackage(g *protogen.GeneratedFile, importPath, symbol string) string {
	qualified := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: protogen.GoImportPath(importPath), GoName: symbol})
	return strings.TrimSuffix(qualified, "."+symbol)
}

type httpImportNames struct {
	Context   string
	Bytes     string
	Fmt       string
	IO        string
	HTTP      string
	URL       string
	ProtoJSON string
	Strconv   string
	Strings   string
}

type httpRequirements struct {
	Bytes   bool
	URL     bool
	Strconv bool
}

type fieldRef struct {
	Expr   string
	Field  *protogen.Field
	Guards []string
}

func extractHTTPBinding(method *protogen.Method) (httpMethod, httpPath, body string) {
	opts := method.Desc.Options()
	if opts == nil {
		return "", "", ""
	}
	rule, ok := proto.GetExtension(opts, annotations.E_Http).(*annotations.HttpRule)
	if !ok || rule == nil {
		return "", "", ""
	}
	switch p := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return "GET", p.Get, rule.Body
	case *annotations.HttpRule_Post:
		return "POST", p.Post, rule.Body
	case *annotations.HttpRule_Put:
		return "PUT", p.Put, rule.Body
	case *annotations.HttpRule_Delete:
		return "DELETE", p.Delete, rule.Body
	case *annotations.HttpRule_Patch:
		return "PATCH", p.Patch, rule.Body
	default:
		return "", "", ""
	}
}

func enrichHTTPServices(file *protogen.File, services []*serviceDesc) (httpRequirements, error) {
	var reqs httpRequirements
	for si, svc := range file.Services {
		for mi, method := range svc.Methods {
			httpMethod, httpPath, body := extractHTTPBinding(method)
			if httpMethod == "" {
				httpMethod = "POST"
				httpPath = fmt.Sprintf("/%s/%s", svc.Desc.FullName(), method.GoName)
			}
			code, methodReqs, err := buildHTTPMethodCode(
				string(svc.Desc.FullName()), method, httpMethod, httpPath, body,
				helperPrefix(file.GeneratedFilenamePrefix),
			)
			if err != nil {
				return reqs, err
			}
			services[si].Methods[mi].HTTPCode = code
			reqs.Bytes = reqs.Bytes || methodReqs.Bytes
			reqs.URL = reqs.URL || methodReqs.URL
			reqs.Strconv = reqs.Strconv || methodReqs.Strconv
		}
	}
	return reqs, nil
}

func buildHTTPMethodCode(service string, method *protogen.Method, httpMethod, httpPath, body, errorPrefix string) (string, httpRequirements, error) {
	var reqs httpRequirements
	pathExpr, pathGuards, pathSelectors, err := buildPathExpr(method.Input, httpPath)
	if err != nil {
		return "", reqs, fmt.Errorf("%s.%s: %w", service, method.GoName, err)
	}
	reqs.URL = len(pathSelectors) > 0

	excluded := make(map[string]bool, len(pathSelectors)+1)
	for _, selector := range pathSelectors {
		excluded[strings.Split(selector, ".")[0]] = true
	}
	if body == "*" {
		if len(pathSelectors) > 0 {
			return "", reqs, fmt.Errorf("%s.%s: body \"*\" with path fields is unsupported", service, method.GoName)
		}
	} else if body != "" {
		ref, err := resolveFieldPath(method.Input, body)
		if err != nil {
			return "", reqs, fmt.Errorf("%s.%s: body %q: %w", service, method.GoName, body, err)
		}
		if ref.Field.Desc.Kind() != protoreflect.MessageKind || ref.Field.Desc.IsList() || ref.Field.Desc.IsMap() {
			return "", reqs, fmt.Errorf("%s.%s: body %q must be a singular message field", service, method.GoName, body)
		}
		excluded[strings.Split(body, ".")[0]] = true
		pathGuards = append(pathGuards, ref.Guards...)
	}

	var query []string
	if body != "*" {
		for _, field := range method.Input.Fields {
			name := string(field.Desc.Name())
			if excluded[name] {
				continue
			}
			if field.Desc.IsMap() || field.Desc.Kind() == protoreflect.MessageKind {
				return "", reqs, fmt.Errorf("%s.%s: query field %q is a message or map", service, method.GoName, name)
			}
			if field.Desc.HasPresence() {
				return "", reqs, fmt.Errorf("%s.%s: query field %q with presence is unsupported", service, method.GoName, name)
			}
			if field.Desc.IsList() && field.Desc.Kind() == protoreflect.MessageKind {
				return "", reqs, fmt.Errorf("%s.%s: repeated message query field %q is unsupported", service, method.GoName, name)
			}
			if field.Desc.IsList() {
				elem, usesStrconv, err := httpValueExpr("v", field, true)
				if err != nil {
					return "", reqs, fmt.Errorf("%s.%s: query field %q: %w", service, method.GoName, name, err)
				}
				reqs.Strconv = reqs.Strconv || usesStrconv
				query = append(query, fmt.Sprintf("\tfor _, v := range req.%s {\n\t\tquery.Add(%s, %s)\n\t}", field.GoName, strconv.Quote(name), elem))
				continue
			}
			value, usesStrconv, err := httpValueExpr("req."+field.GoName, field, false)
			if err != nil {
				return "", reqs, fmt.Errorf("%s.%s: query field %q: %w", service, method.GoName, name, err)
			}
			reqs.Strconv = reqs.Strconv || usesStrconv
			query = append(query, fmt.Sprintf("\tif %s {\n\t\tquery.Set(%s, %s)\n\t}", queryCondition(field), strconv.Quote(name), value))
		}
	}

	var lines []string
	lines = append(lines, "\tif req == nil {", fmt.Sprintf("\t\treturn nil, fmt.Errorf(%s)", strconv.Quote(service+"."+method.GoName+": nil request")), "\t}")
	lines = append(lines, pathGuards...)
	lines = append(lines, "\thttpURL := "+pathExpr)
	if len(query) > 0 {
		reqs.URL = true
		lines = append(lines, "\tu, err := url.Parse(httpURL)", "\tif err != nil {", fmt.Sprintf("\t\treturn nil, fmt.Errorf(%s, err)", strconv.Quote("build "+service+"."+method.GoName+" URL: %w")), "\t}", "\tquery := u.Query()")
		lines = append(lines, query...)
		lines = append(lines, "\tu.RawQuery = query.Encode()", "\thttpURL = u.String()")
	}
	bodyArg := "nil"
	if body != "" {
		reqs.Bytes = true
		var bodyExpr string
		if body == "*" {
			bodyExpr = "req"
		} else {
			ref, err := resolveFieldPath(method.Input, body)
			if err != nil {
				return "", reqs, err
			}
			bodyExpr = ref.Expr
			lines = append(lines, fmt.Sprintf("\tif %s == nil {\n\t\treturn nil, fmt.Errorf(%s)\n\t}", bodyExpr, strconv.Quote(service+"."+method.GoName+": body field "+body+" is nil")))
		}
		lines = append(lines, fmt.Sprintf("\tbodyBytes, err := protojson.MarshalOptions{UseProtoNames: true}.Marshal(%s)", bodyExpr), "\tif err != nil {", fmt.Sprintf("\t\treturn nil, fmt.Errorf(%s, err)", strconv.Quote("encode "+service+"."+method.GoName+" request body: %w")), "\t}", "\tbody := bytes.NewReader(bodyBytes)")
		bodyArg = "body"
	}
	lines = append(lines,
		fmt.Sprintf("\thttpReq, err := http.NewRequestWithContext(ctx, %s, httpURL, %s)", strconv.Quote(httpMethod), bodyArg),
		"\tif err != nil {",
		fmt.Sprintf("\t\treturn nil, fmt.Errorf(%s, err)", strconv.Quote("build "+service+"."+method.GoName+" request: %w")),
		"\t}",
	)
	if body != "" {
		lines = append(lines, "\thttpReq.Header.Set(\"Content-Type\", \"application/json\")")
	}
	lines = append(lines,
		"\thttpResp, err := hc.Do(httpReq)",
		"\tif err != nil {",
		"\t\treturn nil, err",
		"\t}",
		"\tdefer httpResp.Body.Close()",
		"\tresponseBody, err := io.ReadAll(httpResp.Body)",
		"\tif err != nil {",
		"\t\treturn nil, err",
		"\t}",
		"\tif httpResp.StatusCode < http.StatusOK || httpResp.StatusCode >= http.StatusMultipleChoices {",
		fmt.Sprintf("\t\treturn nil, &%sHTTPError{Method: %s, Status: httpResp.StatusCode, Body: responseBody}", errorPrefix, strconv.Quote(service+"."+method.GoName)),
		"\t}",
		fmt.Sprintf("\treply = new(%s)", method.Output.GoIdent.GoName),
		"\tif len(strings.TrimSpace(string(responseBody))) == 0 {",
		"\t\treturn reply, nil",
		"\t}",
		"\tif err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(responseBody, reply); err != nil {",
		fmt.Sprintf("\t\treturn nil, fmt.Errorf(%s, err)", strconv.Quote("decode "+service+"."+method.GoName+" response: %w")),
		"\t}",
		"\treturn reply, nil",
	)
	return strings.Join(lines, "\n"), reqs, nil
}

func buildPathExpr(input *protogen.Message, template string) (string, []string, []string, error) {
	var parts []string
	var guards []string
	var selectors []string
	pos := 0
	for {
		start := strings.IndexByte(template[pos:], '{')
		if start < 0 {
			break
		}
		start += pos
		end := strings.IndexByte(template[start+1:], '}')
		if end < 0 {
			return "", nil, nil, fmt.Errorf("invalid path template %q", template)
		}
		end += start + 1
		if start > pos {
			parts = append(parts, strconv.Quote(template[pos:start]))
		}
		selector := template[start+1 : end]
		if strings.Contains(selector, "=") {
			return "", nil, nil, fmt.Errorf("complex path template %q is unsupported", selector)
		}
		ref, err := resolveFieldPath(input, selector)
		if err != nil {
			return "", nil, nil, fmt.Errorf("path field %q: %w", selector, err)
		}
		value, _, err := httpValueExpr(ref.Expr, ref.Field, false)
		if err != nil {
			return "", nil, nil, fmt.Errorf("path field %q: %w", selector, err)
		}
		parts = append(parts, "url.PathEscape("+value+")")
		guards = append(guards, ref.Guards...)
		selectors = append(selectors, selector)
		pos = end + 1
	}
	if pos < len(template) {
		parts = append(parts, strconv.Quote(template[pos:]))
	}
	if len(parts) == 0 {
		parts = append(parts, strconv.Quote(template))
	}
	return "baseURL + " + strings.Join(parts, " + "), uniqueStrings(guards), selectors, nil
}

func resolveFieldPath(input *protogen.Message, selector string) (fieldRef, error) {
	parts := strings.Split(selector, ".")
	msg := input
	expr := "req"
	var guards []string
	var field *protogen.Field
	for i, part := range parts {
		field = nil
		for _, candidate := range msg.Fields {
			if string(candidate.Desc.Name()) == part || candidate.Desc.JSONName() == part {
				field = candidate
				break
			}
		}
		if field == nil {
			return fieldRef{}, fmt.Errorf("field %q not found", selector)
		}
		expr += "." + field.GoName
		if i == len(parts)-1 {
			break
		}
		if field.Desc.Kind() != protoreflect.MessageKind || field.Message == nil || field.Desc.IsList() || field.Desc.IsMap() {
			return fieldRef{}, fmt.Errorf("field %q is not a message path", parts[i])
		}
		guards = append(guards, expr+" == nil")
		msg = field.Message
	}
	if field == nil {
		return fieldRef{}, fmt.Errorf("empty field selector")
	}
	return fieldRef{Expr: expr, Field: field, Guards: guards}, nil
}

func queryCondition(field *protogen.Field) string {
	expr := "req." + field.GoName
	if field.Desc.Kind() == protoreflect.StringKind {
		return expr + ` != ""`
	}
	if field.Desc.Kind() == protoreflect.BoolKind {
		return expr
	}
	return expr + " != 0"
}
func httpValueExpr(expr string, field *protogen.Field, repeatedElement bool) (string, bool, error) {
	if field.Desc.IsMap() || field.Desc.Kind() == protoreflect.MessageKind || field.Desc.Kind() == protoreflect.GroupKind {
		return "", false, fmt.Errorf("message and map values are unsupported")
	}
	if field.Desc.IsList() && !repeatedElement {
		return "", false, fmt.Errorf("repeated value requires a loop")
	}
	if field.Desc.HasPresence() {
		return "", false, fmt.Errorf("fields with presence are unsupported")
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return expr, false, nil
	case protoreflect.BoolKind:
		return "strconv.FormatBool(" + expr + ")", true, nil
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "strconv.Itoa(int(" + expr + "))", true, nil
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "strconv.FormatInt(" + expr + ", 10)", true, nil
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "strconv.FormatUint(uint64(" + expr + "), 10)", true, nil
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "strconv.FormatUint(" + expr + ", 10)", true, nil
	case protoreflect.FloatKind:
		return "strconv.FormatFloat(float64(" + expr + "), 'f', -1, 32)", true, nil
	case protoreflect.DoubleKind:
		return "strconv.FormatFloat(" + expr + ", 'f', -1, 64)", true, nil
	case protoreflect.EnumKind:
		return "strconv.Itoa(int(" + expr + "))", true, nil
	default:
		return "", false, fmt.Errorf("kind %s is unsupported", field.Desc.Kind())
	}
}

func uniqueStrings(values []string) []string {
	seen := make(map[string]bool, len(values))
	result := make([]string, 0, len(values))
	for _, value := range values {
		if !seen[value] {
			seen[value] = true
			result = append(result, value)
		}
	}
	return result
}

func replaceHTTPImports(code string, imports httpImportNames) string {
	for old, replacement := range map[string]string{
		"context":   imports.Context,
		"bytes":     imports.Bytes,
		"fmt":       imports.Fmt,
		"io":        imports.IO,
		"http":      imports.HTTP,
		"url":       imports.URL,
		"protojson": imports.ProtoJSON,
		"strconv":   imports.Strconv,
		"strings":   imports.Strings,
	} {
		if replacement != "" && replacement != old {
			code = strings.ReplaceAll(code, old+".", replacement+".")
		}
	}
	return code
}

func helperPrefix(filename string) string {
	var b strings.Builder
	for i, r := range filename {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || (i > 0 && r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	prefix := strings.Trim(b.String(), "_")
	if prefix == "" {
		return "Generated"
	}
	if prefix[0] >= '0' && prefix[0] <= '9' {
		return "Generated_" + prefix
	}
	return prefix
}

func splitLines(s string) []string {
	return strings.Split(s, "\n")
}

// ─── Aggregated client file (_client_set.pb.go per *.api package) ───
// Each service proto package follows <domain>.api.<module> (e.g.
// user.api.userToken). Since every proto is compiled in one protoc request,
// group the services by the package up to and including ".api" and emit a
// single file under the corresponding Go directory (e.g.
// biz/user/api/api_client_set.pb.go, package api) exporting RPCServices
// (the fully-qualified service names a follow client dials, one rpcx XClient
// per name) and the <Domain>Client assembly. The assembly is protocol-agnostic,
// so it is emitted regardless of which protocols= flags are enabled.

func generateAggregates(gen *protogen.Plugin) {
	groups := make(map[string][]*protogen.File)
	for _, f := range gen.Files {
		if !f.Generate || len(f.Services) == 0 {
			continue
		}
		key, ok := apiGroupKey(string(f.Desc.Package()))
		if !ok {
			continue
		}
		groups[key] = append(groups[key], f)
	}
	for _, files := range groups {
		generateAggregate(gen, files)
	}
}

// apiGroupKey returns the proto package up to and including the ".api"
// segment, e.g. "user.api.userToken" -> "user.api". Services that do not
// follow the <domain>.api.<module> convention get no aggregate file.
func apiGroupKey(pkg string) (string, bool) {
	segs := strings.Split(pkg, ".")
	for i, seg := range segs {
		if seg == "api" {
			return strings.Join(segs[:i+1], "."), true
		}
	}
	return "", false
}

func generateAggregate(gen *protogen.Plugin, files []*protogen.File) {
	first := files[0]
	importPath := path.Dir(string(first.GoImportPath))
	pkg := path.Base(importPath)
	// proto path is <dir>/<module>/<module>.proto; drop the module dir and
	// the filename to reach the *.api directory.
	dir := path.Dir(path.Dir(first.Desc.Path()))

	g := gen.NewGeneratedFile(path.Join(dir, pkg+"_client_set.pb.go"), protogen.GoImportPath(importPath))
	g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
	g.P()
	g.P("package ", pkg)
	g.P()
	g.P("// RPCServices lists every fully-qualified service name in the ", pkg, " package,")
	g.P("// one per rpcx service. Feed it to the rpcx dialer so a follow client binds")
	g.P("// an XClient for each.")
	g.P("var RPCServices = []string{")
	for _, f := range files {
		for _, svc := range f.Services {
			g.P("\t", g.QualifiedGoIdent(protogen.GoIdent{
				GoImportPath: f.GoImportPath,
				GoName:       svc.GoName + "ServiceName",
			}), ",")
		}
	}
	g.P("}")

	domain := clientDomain(string(first.Desc.Package()))
	if domain == "" {
		return
	}

	structName := domain + "Client"
	g.P()
	g.P("// ", structName, " assembles every generated client in the ", pkg, " package,")
	g.P("// all sharing the same protocol handle.")
	g.P("type ", structName, " struct {")
	for _, f := range files {
		for _, svc := range f.Services {
			g.P("\t", clientFieldName(svc.GoName), " *", g.QualifiedGoIdent(protogen.GoIdent{
				GoImportPath: f.GoImportPath,
				GoName:       svc.GoName + "Client",
			}))
		}
	}
	g.P("}")
	g.P()
	g.P("// New", structName, " routes a (kind, handle, baseURL) triple to each service's")
	g.P("// generated per-protocol constructor.")
	g.P("func New", structName, "(kind string, handle any, baseURL string) *", structName, " {")
	g.P("\treturn &", structName, "{")
	for _, f := range files {
		for _, svc := range f.Services {
			g.P("\t\t", clientFieldName(svc.GoName), ": ", g.QualifiedGoIdent(protogen.GoIdent{
				GoImportPath: f.GoImportPath,
				GoName:       "New" + svc.GoName + "Client",
			}), "(kind, handle, baseURL),")
		}
	}
	g.P("\t}")
	g.P("}")
}

// clientDomain returns the PascalCase domain before ".api", e.g.
// "user.api.userToken" -> "User". Empty when the package has no domain.
func clientDomain(pkg string) string {
	segs := strings.Split(pkg, ".")
	for i, seg := range segs {
		if seg == "api" && i > 0 {
			return strings.ToUpper(segs[i-1][:1]) + segs[i-1][1:]
		}
	}
	return ""
}

// clientFieldName strips a trailing "Api" from a service Go name to get the
// aggregate struct field, e.g. UserTokenApi -> UserToken.
func clientFieldName(goName string) string {
	if strings.HasSuffix(goName, "Api") {
		return goName[:len(goName)-len("Api")]
	}
	return goName
}
