package main

import (
	"path"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

type protocols struct {
	HTTP bool
	GRPC bool
	RPCX bool
	WS   bool
}

func parseProtocols(param string) protocols {
	p := protocols{HTTP: true, GRPC: true, RPCX: true, WS: true}
	if param == "" || !strings.Contains(param, "protocols=") {
		return p
	}
	idx := strings.Index(param, "protocols=")
	rest := param[idx+len("protocols="):]
	var names []string
	for _, part := range strings.Split(rest, ",") {
		if strings.Contains(part, "=") {
			break
		}
		names = append(names, strings.TrimSpace(part))
	}
	enabled := make(map[string]bool)
	for _, name := range names {
		enabled[name] = true
	}
	p.HTTP = enabled["http"]
	p.GRPC = enabled["grpc"]
	p.RPCX = enabled["rpcx"]
	p.WS = enabled["ws"] || enabled["websocket"]
	return p
}

func generateFile(gen *protogen.Plugin, file *protogen.File, protos protocols) {
	if len(file.Services) == 0 {
		return
	}

	pkg := string(file.GoPackageName)

	// Build shared service descriptors (used by both base client and per-protocol files).
	// First pass: collect all type imports needed by the base client struct.
	var baseMethods []methodDesc
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			baseMethods = append(baseMethods, methodDesc{
				Name:      method.GoName,
				FieldName: fieldName(method.GoName),
				Request:   string(method.Input.GoIdent.GoName),
				Reply:     string(method.Output.GoIdent.GoName),
			})
		}
	}
	_ = baseMethods

	// ─── Base client file (_client.pb.go) ───
	baseFilename := file.GeneratedFilenamePrefix + "_client.pb.go"
	bg := gen.NewGeneratedFile(baseFilename, file.GoImportPath)
	bg.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
	bg.P("// source: ", file.Desc.Path())
	bg.P()
	bg.P("package ", file.GoPackageName)
	bg.P()

	bg.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: "context",
		GoName:       "Context",
	})
	// Register imports for all request/reply types
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			bg.QualifiedGoIdent(method.Input.GoIdent)
			bg.QualifiedGoIdent(method.Output.GoIdent)
		}
	}

	buildServices := func(unusedIdent func(protogen.GoIdent) string) []*serviceDesc {
		var services []*serviceDesc
		for _, svc := range file.Services {
			sd := &serviceDesc{
				ServiceType: svc.GoName,
				ServiceName: string(svc.Desc.FullName()),
			}
			for _, method := range svc.Methods {
				md := methodDesc{
					Name:      method.GoName,
					FieldName: fieldName(method.GoName),
					Request:   unusedIdent(method.Input.GoIdent),
					Reply:     unusedIdent(method.Output.GoIdent),
				}
				sd.Methods = append(sd.Methods, md)
			}
			services = append(services, sd)
		}
		return services
	}

	output := generateClient(pkg, buildServices(func(id protogen.GoIdent) string {
		return bg.QualifiedGoIdent(id)
	}))
	for _, line := range splitLines(output) {
		bg.P(line)
	}

	// ─── Per-protocol files ───

	if protos.HTTP {
		filename := file.GeneratedFilenamePrefix + "_client_http.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		// Configure each method's HTTP binding and register request/reply
		// imports. HasBody is computed here, before the import block below,
		// because it decides whether the bytes import is emitted.
		hasBody := false
		for _, svc := range services {
			for i := range svc.Methods {
				m := svc.Methods[i]
				httpMethod := ""
				httpPath := ""
				var params []paramBinding

				for _, ps := range file.Services {
					if ps.GoName != svc.ServiceType {
						continue
					}
					for _, pm := range ps.Methods {
						if pm.GoName != m.Name {
							continue
						}
						httpMethod, httpPath = extractHTTPBinding(pm)
						params = extractPathParams(httpPath)
					}
				}
				svc.Methods[i].HTTPMethod = httpMethod
				svc.Methods[i].HTTPPath = httpPath
				svc.Methods[i].PathParams = params
				svc.Methods[i].HTTPURL = buildURLExpr("baseURL", httpPath, params)
				svc.Methods[i].HasBody = httpMethod == "POST" || httpMethod == "PUT" || httpMethod == "PATCH"
				if svc.Methods[i].HasBody {
					hasBody = true
				}

				// Register imports needed in closure signatures
				for _, ps := range file.Services {
					if ps.GoName != svc.ServiceType {
						continue
					}
					for _, pm := range ps.Methods {
						if pm.GoName != m.Name {
							continue
						}
						g.QualifiedGoIdent(pm.Input.GoIdent)
						g.QualifiedGoIdent(pm.Output.GoIdent)
					}
				}
			}
		}

		// bytes.Buffer is only emitted for methods with a request body; import it
		// only then, or an all-GET service gets an unused bytes import.
		if hasBody {
			g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "bytes", GoName: "Buffer"})
		}
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "encoding/json", GoName: "Encoder"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "fmt", GoName: "Sprint"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "net/http", GoName: "Client"})

		output := generateHTTPClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.GRPC {
		filename := file.GeneratedFilenamePrefix + "_client_grpc.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/grpc", GoName: "ClientConnInterface"})

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateGRPCClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.RPCX {
		filename := file.GeneratedFilenamePrefix + "_client_rpcx.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/smallnest/rpcx/client", GoName: "XClient"})

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateRPCXClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.WS {
		filename := file.GeneratedFilenamePrefix + "_client_ws.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/gorilla/websocket", GoName: "Conn"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "net/http", GoName: "Header"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/protobuf/proto", GoName: "Marshal"})

		// WSDialer lets a caller inject any dialer whose signature matches
		// *websocket.Dialer — for example websocket.NewClient()
		// (github.com/neo532/gofr/transport/websocket), which wires middleware
		// and retry onto the dial. It is self-contained so generated code does
		// not import gofr.
		g.P("// WSDialer dials a websocket endpoint. *websocket.Dialer satisfies it.")
		g.P("type WSDialer interface {")
		g.P("\tDialContext(ctx context.Context, urlStr string, requestHeader http.Header) (*websocket.Conn, *http.Response, error)")
		g.P("}")

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateWSClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	// ─── Client set dispatcher file (_client_set.pb.go) ───
	// A single switch dispatcher per service, keyed by protocol kind string,
	// that routes (kind, handle, baseURL) to the matching per-protocol
	// constructor. The kind strings mirror transport.Kind values so callers
	// can pass them unmodified; generated code does not import gofr.
	filename := file.GeneratedFilenamePrefix + "_client_set.pb.go"
	cs := gen.NewGeneratedFile(filename, file.GoImportPath)
	cs.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
	cs.P("// source: ", file.Desc.Path())
	cs.P()
	cs.P("package ", file.GoPackageName)
	cs.P()

	if protos.GRPC {
		cs.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/grpc", GoName: "ClientConnInterface"})
	}
	if protos.RPCX {
		cs.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/smallnest/rpcx/client", GoName: "XClient"})
	}
	if protos.HTTP {
		cs.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "net/http", GoName: "Client"})
	}

	setServices := buildServices(func(id protogen.GoIdent) string {
		return string(id.GoName)
	})
	setOutput := generateClientSet(&fileDesc{
		PackageName: pkg,
		Services:    setServices,
		HasHTTP:     protos.HTTP,
		HasGRPC:     protos.GRPC,
		HasRPCX:     protos.RPCX,
		HasWS:       protos.WS,
	})
	for _, line := range splitLines(setOutput) {
		cs.P(line)
	}
}

// --- HTTP annotation extraction ---

func extractHTTPBinding(method *protogen.Method) (httpMethod, httpPath string) {
	opts := method.Desc.Options()
	if opts == nil {
		return "", ""
	}
	rule, ok := proto.GetExtension(opts, annotations.E_Http).(*annotations.HttpRule)
	if !ok || rule == nil {
		return "", ""
	}
	switch p := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return "GET", p.Get
	case *annotations.HttpRule_Post:
		return "POST", p.Post
	case *annotations.HttpRule_Put:
		return "PUT", p.Put
	case *annotations.HttpRule_Delete:
		return "DELETE", p.Delete
	case *annotations.HttpRule_Patch:
		return "PATCH", p.Patch
	}
	return "", ""
}

func extractPathParams(path string) (params []paramBinding) {
	for i := 0; i < len(path); i++ {
		if path[i] == '{' {
			start := i + 1
			i++
			for i < len(path) && path[i] != '}' {
				i++
			}
			if start < i {
				name := path[start:i]
				params = append(params, paramBinding{
					ProtoName: name,
					GoField:   snakeToPascal(name),
				})
			}
		}
	}
	return
}

func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func buildURLExpr(prefix, path string, params []paramBinding) string {
	if len(params) == 0 {
		if path == "" {
			return prefix
		}
		return prefix + ` + "` + path + `"`
	}

	var parts []string
	pos := 0
	for _, p := range params {
		braceStart := strings.Index(path[pos:], "{"+p.ProtoName+"}")
		if braceStart < 0 {
			continue
		}
		braceStart += pos
		if braceStart > pos {
			parts = append(parts, `"`+path[pos:braceStart]+`"`)
		}
		parts = append(parts, `fmt.Sprint(req.`+p.GoField+`)`)
		pos = braceStart + len(p.ProtoName) + 2
	}
	if pos < len(path) {
		parts = append(parts, `"`+path[pos:]+`"`)
	}
	return prefix + ` + ` + strings.Join(parts, " + ")
}

func splitLines(s string) []string {
	return strings.Split(s, "\n")
}

// ─── Aggregated client file (_client_set.pb.go per *.api package) ───
// Each service proto package follows <domain>.api.<module> (e.g.
// user.api.userToken). Since every proto is compiled in one protoc request,
// group the services by the package up to and including ".api" and emit a
// single file under the corresponding Go directory (e.g.
// biz/user/api/api_client_set.pb.go, package api) exporting RPCServices
// (the fully-qualified service names a follow client dials, one rpcx XClient
// per name) and the <Domain>Client assembly. The assembly is protocol-agnostic,
// so it is emitted regardless of which protocols= flags are enabled.

func generateAggregates(gen *protogen.Plugin) {
	groups := make(map[string][]*protogen.File)
	for _, f := range gen.Files {
		if !f.Generate || len(f.Services) == 0 {
			continue
		}
		key, ok := apiGroupKey(string(f.Desc.Package()))
		if !ok {
			continue
		}
		groups[key] = append(groups[key], f)
	}
	for _, files := range groups {
		generateAggregate(gen, files)
	}
}

// apiGroupKey returns the proto package up to and including the ".api"
// segment, e.g. "user.api.userToken" -> "user.api". Services that do not
// follow the <domain>.api.<module> convention get no aggregate file.
func apiGroupKey(pkg string) (string, bool) {
	segs := strings.Split(pkg, ".")
	for i, seg := range segs {
		if seg == "api" {
			return strings.Join(segs[:i+1], "."), true
		}
	}
	return "", false
}

func generateAggregate(gen *protogen.Plugin, files []*protogen.File) {
	first := files[0]
	importPath := path.Dir(string(first.GoImportPath))
	pkg := path.Base(importPath)
	// proto path is <dir>/<module>/<module>.proto; drop the module dir and
	// the filename to reach the *.api directory.
	dir := path.Dir(path.Dir(first.Desc.Path()))

	g := gen.NewGeneratedFile(path.Join(dir, pkg+"_client_set.pb.go"), protogen.GoImportPath(importPath))
	g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
	g.P()
	g.P("package ", pkg)
	g.P()
	g.P("// RPCServices lists every fully-qualified service name in the ", pkg, " package,")
	g.P("// one per rpcx service. Feed it to the rpcx dialer so a follow client binds")
	g.P("// an XClient for each.")
	g.P("var RPCServices = []string{")
	for _, f := range files {
		for _, svc := range f.Services {
			g.P("\t", g.QualifiedGoIdent(protogen.GoIdent{
				GoImportPath: f.GoImportPath,
				GoName:       svc.GoName + "ServiceName",
			}), ",")
		}
	}
	g.P("}")

	domain := clientDomain(string(first.Desc.Package()))
	if domain == "" {
		return
	}

	structName := domain + "Client"
	g.P()
	g.P("// ", structName, " assembles every generated client in the ", pkg, " package,")
	g.P("// all sharing the same protocol handle.")
	g.P("type ", structName, " struct {")
	for _, f := range files {
		for _, svc := range f.Services {
			g.P("\t", clientFieldName(svc.GoName), " *", g.QualifiedGoIdent(protogen.GoIdent{
				GoImportPath: f.GoImportPath,
				GoName:       svc.GoName + "Client",
			}))
		}
	}
	g.P("}")
	g.P()
	g.P("// New", structName, " routes a (kind, handle, baseURL) triple to each service's")
	g.P("// generated per-protocol constructor.")
	g.P("func New", structName, "(kind string, handle any, baseURL string) *", structName, " {")
	g.P("\treturn &", structName, "{")
	for _, f := range files {
		for _, svc := range f.Services {
			g.P("\t\t", clientFieldName(svc.GoName), ": ", g.QualifiedGoIdent(protogen.GoIdent{
				GoImportPath: f.GoImportPath,
				GoName:       "New" + svc.GoName + "Client",
			}), "(kind, handle, baseURL),")
		}
	}
	g.P("\t}")
	g.P("}")
}

// clientDomain returns the PascalCase domain before ".api", e.g.
// "user.api.userToken" -> "User". Empty when the package has no domain.
func clientDomain(pkg string) string {
	segs := strings.Split(pkg, ".")
	for i, seg := range segs {
		if seg == "api" && i > 0 {
			return strings.ToUpper(segs[i-1][:1]) + segs[i-1][1:]
		}
	}
	return ""
}

// clientFieldName strips a trailing "Api" from a service Go name to get the
// aggregate struct field, e.g. UserTokenApi -> UserToken.
func clientFieldName(goName string) string {
	if strings.HasSuffix(goName, "Api") {
		return goName[:len(goName)-len("Api")]
	}
	return goName
}
