package main

import (
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

type protocols struct {
	HTTP bool
	GRPC bool
	RPCX bool
	WS   bool
}

func parseProtocols(param string) protocols {
	p := protocols{HTTP: true, GRPC: true, RPCX: true, WS: true}
	if param == "" || !strings.Contains(param, "protocols=") {
		return p
	}
	idx := strings.Index(param, "protocols=")
	rest := param[idx+len("protocols="):]
	var names []string
	for _, part := range strings.Split(rest, ",") {
		if strings.Contains(part, "=") {
			break
		}
		names = append(names, strings.TrimSpace(part))
	}
	enabled := make(map[string]bool)
	for _, name := range names {
		enabled[name] = true
	}
	p.HTTP = enabled["http"]
	p.GRPC = enabled["grpc"]
	p.RPCX = enabled["rpcx"]
	p.WS = enabled["ws"] || enabled["websocket"]
	return p
}

func generateFile(gen *protogen.Plugin, file *protogen.File, protos protocols) {
	if len(file.Services) == 0 {
		return
	}

	pkg := string(file.GoPackageName)

	// Build shared service descriptors (used by both base client and per-protocol files).
	// First pass: collect all type imports needed by the base client struct.
	var baseMethods []methodDesc
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			baseMethods = append(baseMethods, methodDesc{
				Name:      method.GoName,
				FieldName: fieldName(method.GoName),
				Request:   string(method.Input.GoIdent.GoName),
				Reply:     string(method.Output.GoIdent.GoName),
			})
		}
	}
	_ = baseMethods

	// ─── Base client file (_client.pb.go) ───
	baseFilename := file.GeneratedFilenamePrefix + "_client.pb.go"
	bg := gen.NewGeneratedFile(baseFilename, file.GoImportPath)
	bg.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
	bg.P("// source: ", file.Desc.Path())
	bg.P()
	bg.P("package ", file.GoPackageName)
	bg.P()

	bg.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: "context",
		GoName:       "Context",
	})
	// Register imports for all request/reply types
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			bg.QualifiedGoIdent(method.Input.GoIdent)
			bg.QualifiedGoIdent(method.Output.GoIdent)
		}
	}

	buildServices := func(unusedIdent func(protogen.GoIdent) string) []*serviceDesc {
		var services []*serviceDesc
		for _, svc := range file.Services {
			sd := &serviceDesc{
				ServiceType: svc.GoName,
				ServiceName: string(svc.Desc.FullName()),
			}
			for _, method := range svc.Methods {
				md := methodDesc{
					Name:      method.GoName,
					FieldName: fieldName(method.GoName),
					Request:   unusedIdent(method.Input.GoIdent),
					Reply:     unusedIdent(method.Output.GoIdent),
				}
				sd.Methods = append(sd.Methods, md)
			}
			services = append(services, sd)
		}
		return services
	}

	output := generateClient(pkg, buildServices(func(id protogen.GoIdent) string {
		return bg.QualifiedGoIdent(id)
	}))
	for _, line := range splitLines(output) {
		bg.P(line)
	}

	// ─── Per-protocol files ───

	if protos.HTTP {
		filename := file.GeneratedFilenamePrefix + "_client_http.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "bytes", GoName: "Buffer"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "encoding/json", GoName: "Encoder"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "fmt", GoName: "Sprint"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "net/http", GoName: "Client"})

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		for _, svc := range services {
			for i := range svc.Methods {
				m := svc.Methods[i]
				httpMethod := ""
				httpPath := ""
				var params []paramBinding

				for _, ps := range file.Services {
					if ps.GoName != svc.ServiceType {
						continue
					}
					for _, pm := range ps.Methods {
						if pm.GoName != m.Name {
							continue
						}
						httpMethod, httpPath = extractHTTPBinding(pm)
						params = extractPathParams(httpPath)
					}
				}
				svc.Methods[i].HTTPMethod = httpMethod
				svc.Methods[i].HTTPPath = httpPath
				svc.Methods[i].PathParams = params
				svc.Methods[i].HTTPURL = buildURLExpr("baseURL", httpPath, params)
				svc.Methods[i].HasBody = httpMethod == "POST" || httpMethod == "PUT" || httpMethod == "PATCH"

				// Register imports needed in closure signatures
				for _, ps := range file.Services {
					if ps.GoName != svc.ServiceType {
						continue
					}
					for _, pm := range ps.Methods {
						if pm.GoName != m.Name {
							continue
						}
						g.QualifiedGoIdent(pm.Input.GoIdent)
						g.QualifiedGoIdent(pm.Output.GoIdent)
					}
				}
			}
		}

		output := generateHTTPClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.GRPC {
		filename := file.GeneratedFilenamePrefix + "_client_grpc.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/grpc", GoName: "ClientConnInterface"})

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateGRPCClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.RPCX {
		filename := file.GeneratedFilenamePrefix + "_client_rpcx.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/smallnest/rpcx/client", GoName: "XClient"})

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateRPCXClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}

	if protos.WS {
		filename := file.GeneratedFilenamePrefix + "_client_ws.pb.go"
		g := gen.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-go-client. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "context", GoName: "Context"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/gorilla/websocket", GoName: "Dialer"})
		g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/protobuf/proto", GoName: "Marshal"})

		services := buildServices(func(id protogen.GoIdent) string {
			return g.QualifiedGoIdent(id)
		})

		output := generateWSClient(pkg, services)
		for _, line := range splitLines(output) {
			g.P(line)
		}
	}
}

// --- HTTP annotation extraction ---

func extractHTTPBinding(method *protogen.Method) (httpMethod, httpPath string) {
	opts := method.Desc.Options()
	if opts == nil {
		return "", ""
	}
	rule, ok := proto.GetExtension(opts, annotations.E_Http).(*annotations.HttpRule)
	if !ok || rule == nil {
		return "", ""
	}
	switch p := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return "GET", p.Get
	case *annotations.HttpRule_Post:
		return "POST", p.Post
	case *annotations.HttpRule_Put:
		return "PUT", p.Put
	case *annotations.HttpRule_Delete:
		return "DELETE", p.Delete
	case *annotations.HttpRule_Patch:
		return "PATCH", p.Patch
	}
	return "", ""
}

func extractPathParams(path string) (params []paramBinding) {
	for i := 0; i < len(path); i++ {
		if path[i] == '{' {
			start := i + 1
			i++
			for i < len(path) && path[i] != '}' {
				i++
			}
			if start < i {
				name := path[start:i]
				params = append(params, paramBinding{
					ProtoName: name,
					GoField:   snakeToPascal(name),
				})
			}
		}
	}
	return
}

func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func buildURLExpr(prefix, path string, params []paramBinding) string {
	if len(params) == 0 {
		if path == "" {
			return prefix
		}
		return prefix + ` + "` + path + `"`
	}

	var parts []string
	pos := 0
	for _, p := range params {
		braceStart := strings.Index(path[pos:], "{"+p.ProtoName+"}")
		if braceStart < 0 {
			continue
		}
		braceStart += pos
		if braceStart > pos {
			parts = append(parts, `"`+path[pos:braceStart]+`"`)
		}
		parts = append(parts, `fmt.Sprint(req.`+p.GoField+`)`)
		pos = braceStart + len(p.ProtoName) + 2
	}
	if pos < len(path) {
		parts = append(parts, `"`+path[pos:]+`"`)
	}
	return prefix + ` + ` + strings.Join(parts, " + ")
}

func splitLines(s string) []string {
	return strings.Split(s, "\n")
}
