package main

import (
	"fmt"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		protos := parseProtocols(gen.Request.GetParameter())
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f, protos)
		}
		return nil
	})
}

// protocols controls which protocol registration files are generated.
type protocols struct {
	HTTP    bool
	GRPC    bool
	RPCX    bool
	OpenAPI bool
}

// parseProtocols parses --go-svc_opt=protocols=http,grpc from the protoc parameter.
// Defaults to all protocols enabled.
// The parameter format is: [module=...,]protocols=http,grpc,rpcx,openapi
// Note: commas inside the protocols= value are handled by finding "protocols="
// and taking everything after it until the next "key=" pattern or end-of-string.
func parseProtocols(param string) protocols {
	p := protocols{HTTP: true, GRPC: true, RPCX: true, OpenAPI: true}
	if param == "" || !strings.Contains(param, "protocols=") {
		return p
	}
	// Find the protocols= substring and grab everything after it
	idx := strings.Index(param, "protocols=")
	rest := param[idx+len("protocols="):]
	// Split by comma to get individual protocol names
	// (stop at next key= pattern if present)
	var names []string
	for _, part := range strings.Split(rest, ",") {
		if strings.Contains(part, "=") {
			break // stop at next key=value pair
		}
		names = append(names, strings.TrimSpace(part))
	}
	enabled := make(map[string]bool)
	for _, name := range names {
		enabled[name] = true
	}
	p.HTTP = enabled["http"]
	p.GRPC = enabled["grpc"]
	p.RPCX = enabled["rpcx"]
	p.OpenAPI = enabled["openapi"]
	return p
}

func generateFile(gen *protogen.Plugin, file *protogen.File, protos protocols) {
	if len(file.Services) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_svc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// Register imports needed by the svc template
	g.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: "context",
		GoName:       "Context",
	})
	g.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport"),
		GoName:       "ServiceDesc",
	})

	var services []*serviceDesc
	for _, svc := range file.Services {
		sd := &serviceDesc{
			ServiceType: svc.GoName,
			ServiceName: string(svc.Desc.FullName()),
		}
		for _, method := range svc.Methods {
			httpMethod, httpPath := extractHTTPBinding(method)
			routerPath := httpPath
			if routerPath == "" {
				routerPath = fmt.Sprintf("/%s/%s", sd.ServiceName, method.GoName)
			} else {
				routerPath = toHTTPRouterPath(routerPath)
			}
			sd.Methods = append(sd.Methods, methodDesc{
				Name:       method.GoName,
				Request:    g.QualifiedGoIdent(method.Input.GoIdent),
				Reply:      g.QualifiedGoIdent(method.Output.GoIdent),
				HTTPMethod: httpMethod,
				HTTPPath:   httpPath,
				RouterPath: routerPath,
				PathParams: extractPathParams(httpPath),
			})
		}
		services = append(services, sd)
	}

	// Build message definitions for OpenAPI spec.
	messageDefs := buildMessageDefs(file.Services)

	output := generate(string(file.GoPackageName), services)
	for _, line := range splitLines(output) {
		g.P(line)
	}

	if protos.HTTP {
		httpFilename := file.GeneratedFilenamePrefix + "_http.pb.go"
		hg := gen.NewGeneratedFile(httpFilename, file.GoImportPath)
		hg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		hg.P("// source: ", file.Desc.Path())
		hg.P()
		hg.P("package ", file.GoPackageName)
		hg.P()

		// Register the transport/http package import
		hg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/http"),
			GoName:       "Server",
		})
		hg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		hg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "strings",
			GoName:       "Index",
		})

		httpOutput := generateHTTP(string(file.GoPackageName), services)
		for _, line := range splitLines(httpOutput) {
			hg.P(line)
		}
	}

	if protos.GRPC {
		grpcFilename := file.GeneratedFilenamePrefix + "_grpc.pb.go"
		gg := gen.NewGeneratedFile(grpcFilename, file.GoImportPath)
		gg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		gg.P("// source: ", file.Desc.Path())
		gg.P()
		gg.P("package ", file.GoPackageName)
		gg.P()

		// Register imports needed by the grpc template
		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/grpc"),
			GoName:       "Server",
		})
		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "strings",
			GoName:       "Index",
		})
		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "context",
			GoName:       "Context",
		})
		// Register method request/reply type imports (e.g. emptypb.Empty)
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				gg.QualifiedGoIdent(method.Input.GoIdent)
				gg.QualifiedGoIdent(method.Output.GoIdent)
			}
		}

		grpcOutput := generateGRPC(string(file.GoPackageName), services)
		for _, line := range splitLines(grpcOutput) {
			gg.P(line)
		}
	}

	if protos.RPCX {
		rpcxFilename := file.GeneratedFilenamePrefix + "_rpcx.pb.go"
		rg := gen.NewGeneratedFile(rpcxFilename, file.GoImportPath)
		rg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		rg.P("// source: ", file.Desc.Path())
		rg.P()
		rg.P("package ", file.GoPackageName)
		rg.P()

		// Register imports needed by the rpcx template
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/rpcx"),
			GoName:       "Server",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "strings",
			GoName:       "Index",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "context",
			GoName:       "Context",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("google.golang.org/protobuf/proto"),
			GoName:       "Merge",
		})
		// Register method request/reply type imports (e.g. emptypb.Empty)
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				rg.QualifiedGoIdent(method.Input.GoIdent)
				rg.QualifiedGoIdent(method.Output.GoIdent)
			}
		}

		rpcxOutput := generateRPCX(string(file.GoPackageName), services)
		for _, line := range splitLines(rpcxOutput) {
			rg.P(line)
		}
	}

	if protos.OpenAPI {
		openapiFilename := file.GeneratedFilenamePrefix + ".swagger.json"
		og := gen.NewGeneratedFile(openapiFilename, file.GoImportPath)
		og.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		og.P("// source: ", file.Desc.Path())
		og.P()
		openapiOutput := generateOpenAPI(string(file.GoPackageName), services, messageDefs)
		for _, line := range splitLines(openapiOutput) {
			og.P(line)
		}
	}
}

// buildMessageDefs collects unique message definitions from all service methods.
func buildMessageDefs(services []*protogen.Service) map[string][]openapiField {
	defs := make(map[string][]openapiField)
	for _, svc := range services {
		for _, method := range svc.Methods {
			reqKey := messageDefKey(method.Input)
			if _, ok := defs[reqKey]; !ok {
				defs[reqKey] = extractOpenAPIFields(method.Input)
			}
			repKey := messageDefKey(method.Output)
			if _, ok := defs[repKey]; !ok {
				defs[repKey] = extractOpenAPIFields(method.Output)
			}
		}
	}
	return defs
}

// messageDefKey creates a unique definition key for a protobuf message.
func messageDefKey(m *protogen.Message) string {
	return string(m.Desc.FullName())
}

// extractOpenAPIFields extracts OpenAPI field info from a protobuf message.
func extractOpenAPIFields(m *protogen.Message) []openapiField {
	var fields []openapiField
	for _, f := range m.Fields {
		of := openapiField{Name: string(f.Desc.Name())}
		switch f.Desc.Kind() {
		case protoreflect.DoubleKind:
			of.Type, of.Format = "number", "double"
		case protoreflect.FloatKind:
			of.Type, of.Format = "number", "float"
		case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
			of.Type, of.Format = "integer", "int32"
		case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.BoolKind:
			of.Type = "boolean"
		case protoreflect.StringKind:
			of.Type = "string"
		case protoreflect.BytesKind:
			of.Type, of.Format = "string", "byte"
		case protoreflect.EnumKind:
			of.Type = "string"
		case protoreflect.MessageKind, protoreflect.GroupKind:
			of.Ref = messageDefKey(f.Message)
		}
		if f.Desc.IsList() {
			of.Repeated = true
		}
		fields = append(fields, of)
	}
	return fields
}

func splitLines(s string) []string {
	var lines []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	if start < len(s) {
		lines = append(lines, s[start:])
	}
	return lines
}

// extractHTTPBinding reads google.api.http annotation from a proto method.
func extractHTTPBinding(method *protogen.Method) (httpMethod, httpPath string) {
	opts := method.Desc.Options()
	if opts == nil {
		return "", ""
	}
	rule, ok := proto.GetExtension(opts, annotations.E_Http).(*annotations.HttpRule)
	if !ok || rule == nil {
		return "", ""
	}
	switch p := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return "GET", p.Get
	case *annotations.HttpRule_Post:
		return "POST", p.Post
	case *annotations.HttpRule_Put:
		return "PUT", p.Put
	case *annotations.HttpRule_Delete:
		return "DELETE", p.Delete
	case *annotations.HttpRule_Patch:
		return "PATCH", p.Patch
	}
	return "", ""
}

// toHTTPRouterPath converts {param} to :param for httprouter.
func toHTTPRouterPath(p string) string {
	var b strings.Builder
	b.Grow(len(p))
	for i := 0; i < len(p); i++ {
		if p[i] == '{' {
			b.WriteByte(':')
			i++
			for i < len(p) && p[i] != '}' {
				b.WriteByte(p[i])
				i++
			}
		} else {
			b.WriteByte(p[i])
		}
	}
	return b.String()
}

// extractPathParams extracts path parameter names and their Go field names from an HTTP path.
// e.g. "/api/v1/hello/{name}" -> [{ProtoName:"name", GoField:"Name"}]
func extractPathParams(path string) (params []paramBinding) {
	for i := 0; i < len(path); i++ {
		if path[i] == '{' {
			start := i + 1
			i++
			for i < len(path) && path[i] != '}' {
				i++
			}
			if start < i {
				name := path[start:i]
				params = append(params, paramBinding{
					ProtoName: name,
					GoField:   snakeToPascal(name),
				})
			}
		}
	}
	return
}

// snakeToPascal converts snake_case to PascalCase.
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}
