package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// protocols controls which protocol registration files are generated.
type protocols struct {
	HTTP    bool
	GRPC    bool
	RPCX    bool
	Websocket bool
	OpenAPI bool
}

// parseProtocols parses --go-svc_opt=protocols=http,grpc from the protoc parameter.
// Defaults to all protocols enabled.
// The parameter format is: [module=...,]protocols=http,grpc,rpcx,openapi
// Note: commas inside the protocols= value are handled by finding "protocols="
// and taking everything after it until the next "key=" pattern or end-of-string.
func parseProtocols(param string) protocols {
	p := protocols{HTTP: true, GRPC: true, RPCX: true, Websocket: true, OpenAPI: true}
	if param == "" || !strings.Contains(param, "protocols=") {
		return p
	}
	idx := strings.Index(param, "protocols=")
	rest := param[idx+len("protocols="):]
	var names []string
	for _, part := range strings.Split(rest, ",") {
		if strings.Contains(part, "=") {
			break
		}
		names = append(names, strings.TrimSpace(part))
	}
	enabled := make(map[string]bool)
	for _, name := range names {
		enabled[name] = true
	}
	p.HTTP = enabled["http"]
	p.GRPC = enabled["grpc"]
	p.RPCX = enabled["rpcx"]
	p.Websocket = enabled["websocket"]
	p.OpenAPI = enabled["openapi"]
	return p
}

func generateFile(gen *protogen.Plugin, file *protogen.File, protos protocols) {
	if len(file.Services) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_svc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	g.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: "context",
		GoName:       "Context",
	})
	g.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport"),
		GoName:       "ServiceDesc",
	})

	var services []*serviceDesc
	for _, svc := range file.Services {
		sd := &serviceDesc{
			ServiceType: svc.GoName,
			ServiceName: string(svc.Desc.FullName()),
		}
		for _, method := range svc.Methods {
			httpMethod, httpPath := extractHTTPBinding(method)
			routerPath := httpPath
			if routerPath == "" {
				routerPath = fmt.Sprintf("/%s/%s", sd.ServiceName, method.GoName)
			} else {
				routerPath = toHTTPRouterPath(routerPath)
			}
			sd.Methods = append(sd.Methods, methodDesc{
				Name:       method.GoName,
				Request:    g.QualifiedGoIdent(method.Input.GoIdent),
				Reply:      g.QualifiedGoIdent(method.Output.GoIdent),
				HTTPMethod: httpMethod,
				HTTPPath:   httpPath,
				RouterPath: routerPath,
				PathParams: extractPathParams(httpPath),
			})
		}
		services = append(services, sd)
	}

	messageDefs := buildMessageDefs(file.Services)

	output := generate(string(file.GoPackageName), services)
	for _, line := range splitLines(output) {
		g.P(line)
	}

	if protos.HTTP {
		httpFilename := file.GeneratedFilenamePrefix + "_http.pb.go"
		hg := gen.NewGeneratedFile(httpFilename, file.GoImportPath)
		hg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		hg.P("// source: ", file.Desc.Path())
		hg.P()
		hg.P("package ", file.GoPackageName)
		hg.P()

		hg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/http"),
			GoName:       "Server",
		})
		hg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})

		httpOutput := generateHTTP(string(file.GoPackageName), services)
		for _, line := range splitLines(httpOutput) {
			hg.P(line)
		}
	}

	if protos.GRPC {
		grpcFilename := file.GeneratedFilenamePrefix + "_grpc.pb.go"
		gg := gen.NewGeneratedFile(grpcFilename, file.GoImportPath)
		gg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		gg.P("// source: ", file.Desc.Path())
		gg.P()
		gg.P("package ", file.GoPackageName)
		gg.P()

		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/grpc"),
			GoName:       "Server",
		})
		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "context",
			GoName:       "Context",
		})
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				gg.QualifiedGoIdent(method.Input.GoIdent)
			}
		}

		grpcOutput := generateGRPC(string(file.GoPackageName), services)
		for _, line := range splitLines(grpcOutput) {
			gg.P(line)
		}
	}

	if protos.RPCX {
		rpcxFilename := file.GeneratedFilenamePrefix + "_rpcx.pb.go"
		rg := gen.NewGeneratedFile(rpcxFilename, file.GoImportPath)
		rg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		rg.P("// source: ", file.Desc.Path())
		rg.P()
		rg.P("package ", file.GoPackageName)
		rg.P()

		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/rpcx"),
			GoName:       "Server",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "context",
			GoName:       "Context",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("google.golang.org/protobuf/proto"),
			GoName:       "Merge",
		})
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				rg.QualifiedGoIdent(method.Input.GoIdent)
				rg.QualifiedGoIdent(method.Output.GoIdent)
			}
		}

		rpcxOutput := generateRPCX(string(file.GoPackageName), services)
		for _, line := range splitLines(rpcxOutput) {
			rg.P(line)
		}
	}

	if protos.Websocket {
		wsFilename := file.GeneratedFilenamePrefix + "_ws.pb.go"
		wg := gen.NewGeneratedFile(wsFilename, file.GoImportPath)
		wg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		wg.P("// source: ", file.Desc.Path())
		wg.P()
		wg.P("package ", file.GoPackageName)
		wg.P()

		wg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/websocket"),
			GoName:       "Server",
		})
		wg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		wg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "context",
			GoName:       "Context",
		})
		wg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("google.golang.org/protobuf/proto"),
			GoName:       "Marshal",
		})
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				wg.QualifiedGoIdent(method.Input.GoIdent)
			}
		}

		wsOutput := generateWebSocket(string(file.GoPackageName), services)
		for _, line := range splitLines(wsOutput) {
			wg.P(line)
		}
	}

	if protos.OpenAPI {
		openapiFilename := file.GeneratedFilenamePrefix + ".swagger.json"
		og := gen.NewGeneratedFile(openapiFilename, file.GoImportPath)
		og.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		og.P("// source: ", file.Desc.Path())
		og.P()
		openapiOutput := generateOpenAPI(string(file.GoPackageName), services, messageDefs)
		for _, line := range splitLines(openapiOutput) {
			og.P(line)
		}
	}
}

// buildMessageDefs collects unique message definitions from all service methods.
func buildMessageDefs(services []*protogen.Service) map[string][]openapiField {
	defs := make(map[string][]openapiField)
	for _, svc := range services {
		for _, method := range svc.Methods {
			reqKey := messageDefKey(method.Input)
			if _, ok := defs[reqKey]; !ok {
				defs[reqKey] = extractOpenAPIFields(method.Input)
			}
			repKey := messageDefKey(method.Output)
			if _, ok := defs[repKey]; !ok {
				defs[repKey] = extractOpenAPIFields(method.Output)
			}
		}
	}
	return defs
}

// extractOpenAPIFields extracts OpenAPI field info from a protobuf message.
func extractOpenAPIFields(m *protogen.Message) []openapiField {
	var fields []openapiField
	for _, f := range m.Fields {
		of := openapiField{Name: string(f.Desc.Name())}
		switch f.Desc.Kind() {
		case protoreflect.DoubleKind:
			of.Type, of.Format = "number", "double"
		case protoreflect.FloatKind:
			of.Type, of.Format = "number", "float"
		case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
			of.Type, of.Format = "integer", "int32"
		case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.BoolKind:
			of.Type = "boolean"
		case protoreflect.StringKind:
			of.Type = "string"
		case protoreflect.BytesKind:
			of.Type, of.Format = "string", "byte"
		case protoreflect.EnumKind:
			of.Type = "string"
		case protoreflect.MessageKind, protoreflect.GroupKind:
			of.Ref = messageDefKey(f.Message)
		}
		if f.Desc.IsList() {
			of.Repeated = true
		}
		fields = append(fields, of)
	}
	return fields
}

// messageDefKey creates a unique definition key for a protobuf message.
func messageDefKey(m *protogen.Message) string {
	return string(m.Desc.FullName())
}
