package main

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// protocols controls which protocol registration files are generated.
type protocols struct {
	HTTP    bool
	GRPC    bool
	RPCX    bool
	Websocket bool
	OpenAPI bool
}

// parseProtocols parses --go-svc_opt=protocols=http,grpc from the protoc parameter.
// Defaults to all protocols enabled.
// The parameter format is: [module=...,]protocols=http,grpc,rpcx,openapi
// Note: commas inside the protocols= value are handled by finding "protocols="
// and taking everything after it until the next "key=" pattern or end-of-string.
func parseProtocols(param string) protocols {
	p := protocols{HTTP: true, GRPC: true, RPCX: true, Websocket: true, OpenAPI: true}
	if param == "" || !strings.Contains(param, "protocols=") {
		return p
	}
	idx := strings.Index(param, "protocols=")
	rest := param[idx+len("protocols="):]
	var names []string
	for _, part := range strings.Split(rest, ",") {
		if strings.Contains(part, "=") {
			break
		}
		names = append(names, strings.TrimSpace(part))
	}
	enabled := make(map[string]bool)
	for _, name := range names {
		enabled[name] = true
	}
	p.HTTP = enabled["http"]
	p.GRPC = enabled["grpc"]
	p.RPCX = enabled["rpcx"]
	p.Websocket = enabled["websocket"]
	p.OpenAPI = enabled["openapi"]
	return p
}

func generateFile(gen *protogen.Plugin, file *protogen.File, protos protocols) {
	if len(file.Services) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_svc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	g.QualifiedGoIdent(protogen.GoIdent{
		GoImportPath: "context",
		GoName:       "Context",
	})

	var services []*serviceDesc
	for _, svc := range file.Services {
		sd := &serviceDesc{
			ServiceType: svc.GoName,
			ServiceName: string(svc.Desc.FullName()),
		}
		for _, method := range svc.Methods {
			httpMethod, httpPath := extractHTTPBinding(method)
			if httpMethod == "" {
				httpMethod = "POST"
			}
			routerPath := httpPath
			if routerPath == "" {
				routerPath = fmt.Sprintf("/%s/%s", sd.ServiceName, method.GoName)
			} else {
				routerPath = toHTTPRouterPath(routerPath)
			}
			sd.Methods = append(sd.Methods, methodDesc{
				Name:          method.GoName,
				Request:       g.QualifiedGoIdent(method.Input.GoIdent),
				RequestType:   method.Input.GoIdent.GoName,
				RequestImport: method.Input.GoIdent.GoImportPath,
				Reply:         g.QualifiedGoIdent(method.Output.GoIdent),
				HTTPMethod:    httpMethod,
				HTTPPath:      httpPath,
				RouterPath:    routerPath,
				PathParams:    enrichPathParams(method, extractPathParams(httpPath)),
			})
		}
		services = append(services, sd)
	}

	messageDefs := buildMessageDefs(file.Services)

	output := generate(string(file.GoPackageName), services)
	for _, line := range splitLines(output) {
		g.P(line)
	}

	if protos.HTTP {
		httpFilename := file.GeneratedFilenamePrefix + "_http.pb.go"
		hg := gen.NewGeneratedFile(httpFilename, file.GoImportPath)
		hg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		hg.P("// source: ", file.Desc.Path())
		hg.P()
		hg.P("package ", file.GoPackageName)
		hg.P()

		hg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/http"),
			GoName:       "Server",
		})
		hg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				hg.QualifiedGoIdent(method.Input.GoIdent)
			}
		}
		if needStrconvImport(services) {
			hg.QualifiedGoIdent(protogen.GoIdent{
				GoImportPath: "strconv",
				GoName:       "ParseInt",
			})
		}

		httpOutput := generateHTTP(string(file.GoPackageName), services)
		for _, line := range splitLines(httpOutput) {
			hg.P(line)
		}

		// Emit the Service/Method -> HTTP binding table so a gRPC/rpcx call can
		// be replayed as a curl against the HTTP endpoint (see http.Route).
		hg.P()
		hg.P("// HTTPRoutes maps each gRPC full method (Service/Method) to its HTTP binding,")
		hg.P("// so a gRPC/rpcx call can be replayed as a curl against the HTTP endpoint.")
		hg.P("var HTTPRoutes = map[string]http.Route{")
		for _, svc := range services {
			for _, m := range svc.Methods {
				path := m.HTTPPath
				if path == "" {
					path = m.RouterPath
				}
				hg.P(strconv.Quote(svc.ServiceName+"/"+m.Name) + ": {Service: " +
					strconv.Quote(svc.ServiceName) + ", Method: " +
					strconv.Quote(m.Name) + ", HTTPMethod: " +
					strconv.Quote(m.HTTPMethod) + ", Path: " +
					strconv.Quote(path) + "},")
			}
		}
		hg.P("}")
		hg.P()
		hg.P("func init() { http.RegisterRoutes(HTTPRoutes) }")
		hg.P()

		if hasPathParams(services) {
			emitHTTPPathParams(hg, services)
		}
	}

	if protos.GRPC {
		grpcFilename := file.GeneratedFilenamePrefix + "_grpc.pb.go"
		gg := gen.NewGeneratedFile(grpcFilename, file.GoImportPath)
		gg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		gg.P("// source: ", file.Desc.Path())
		gg.P()
		gg.P("package ", file.GoPackageName)
		gg.P()

		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/grpc"),
			GoName:       "Server",
		})
		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		gg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "context",
			GoName:       "Context",
		})
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				gg.QualifiedGoIdent(method.Input.GoIdent)
			}
		}

		grpcOutput := generateGRPC(string(file.GoPackageName), services)
		for _, line := range splitLines(grpcOutput) {
			gg.P(line)
		}
	}

	if protos.RPCX {
		rpcxFilename := file.GeneratedFilenamePrefix + "_rpcx.pb.go"
		rg := gen.NewGeneratedFile(rpcxFilename, file.GoImportPath)
		rg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		rg.P("// source: ", file.Desc.Path())
		rg.P()
		rg.P("package ", file.GoPackageName)
		rg.P()

		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/rpcx"),
			GoName:       "Server",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "context",
			GoName:       "Context",
		})
		rg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("google.golang.org/protobuf/proto"),
			GoName:       "Merge",
		})
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				rg.QualifiedGoIdent(method.Input.GoIdent)
				rg.QualifiedGoIdent(method.Output.GoIdent)
			}
		}

		rpcxOutput := generateRPCX(string(file.GoPackageName), services)
		for _, line := range splitLines(rpcxOutput) {
			rg.P(line)
		}
	}

	if protos.Websocket {
		wsFilename := file.GeneratedFilenamePrefix + "_ws.pb.go"
		wg := gen.NewGeneratedFile(wsFilename, file.GoImportPath)
		wg.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		wg.P("// source: ", file.Desc.Path())
		wg.P()
		wg.P("package ", file.GoPackageName)
		wg.P()

		wg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("github.com/neo532/gofr/transport/websocket"),
			GoName:       "Server",
		})
		wg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "reflect",
			GoName:       "Type",
		})
		wg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: "context",
			GoName:       "Context",
		})
		wg.QualifiedGoIdent(protogen.GoIdent{
			GoImportPath: protogen.GoImportPath("google.golang.org/protobuf/proto"),
			GoName:       "Marshal",
		})
		for _, svc := range file.Services {
			for _, method := range svc.Methods {
				wg.QualifiedGoIdent(method.Input.GoIdent)
			}
		}

		wsOutput := generateWebSocket(string(file.GoPackageName), services)
		for _, line := range splitLines(wsOutput) {
			wg.P(line)
		}
	}

	if protos.OpenAPI {
		openapiFilename := file.GeneratedFilenamePrefix + ".swagger.json"
		og := gen.NewGeneratedFile(openapiFilename, file.GoImportPath)
		og.P("// Code generated by protoc-gen-go-svc. DO NOT EDIT.")
		og.P("// source: ", file.Desc.Path())
		og.P()
		openapiOutput := generateOpenAPI(string(file.GoPackageName), services, messageDefs)
		for _, line := range splitLines(openapiOutput) {
			og.P(line)
		}
	}
}

// buildMessageDefs collects unique message definitions from all service methods.
func buildMessageDefs(services []*protogen.Service) map[string][]openapiField {
	defs := make(map[string][]openapiField)
	for _, svc := range services {
		for _, method := range svc.Methods {
			reqKey := messageDefKey(method.Input)
			if _, ok := defs[reqKey]; !ok {
				defs[reqKey] = extractOpenAPIFields(method.Input)
			}
			repKey := messageDefKey(method.Output)
			if _, ok := defs[repKey]; !ok {
				defs[repKey] = extractOpenAPIFields(method.Output)
			}
		}
	}
	return defs
}

// extractOpenAPIFields extracts OpenAPI field info from a protobuf message.
func extractOpenAPIFields(m *protogen.Message) []openapiField {
	var fields []openapiField
	for _, f := range m.Fields {
		of := openapiField{Name: string(f.Desc.Name())}
		switch f.Desc.Kind() {
		case protoreflect.DoubleKind:
			of.Type, of.Format = "number", "double"
		case protoreflect.FloatKind:
			of.Type, of.Format = "number", "float"
		case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
			of.Type, of.Format = "integer", "int32"
		case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
			of.Type, of.Format = "integer", "int64"
		case protoreflect.BoolKind:
			of.Type = "boolean"
		case protoreflect.StringKind:
			of.Type = "string"
		case protoreflect.BytesKind:
			of.Type, of.Format = "string", "byte"
		case protoreflect.EnumKind:
			of.Type = "string"
		case protoreflect.MessageKind, protoreflect.GroupKind:
			of.Ref = messageDefKey(f.Message)
		}
		if f.Desc.IsList() {
			of.Repeated = true
		}
		fields = append(fields, of)
	}
	return fields
}

// messageDefKey creates a unique definition key for a protobuf message.
func messageDefKey(m *protogen.Message) string {
	return string(m.Desc.FullName())
}

// enrichPathParams resolves each path param to its actual proto field and
// precomputes the zero-reflection bind statement used by generated HTTP decoders,
// plus the value expression used by the generated ReplayPathParams method.
func enrichPathParams(method *protogen.Method, params []paramBinding) []paramBinding {
	for i := range params {
		p := &params[i]
		f := findFieldByName(method.Input, p.ProtoName)
		if f == nil {
			p.BindStmt = fmt.Sprintf("req.%s = ctx.PathValue(%q)", p.GoField, p.ProtoName)
			p.ValueExpr = `""`
			continue
		}
		p.GoField = f.GoName
		p.BindStmt = pathBindStmt(p.GoField, p.ProtoName, f)
		p.ValueExpr = pathValueExpr(f)
	}
	return params
}

// pathValueExpr returns a Go expression that renders a request field as its
// path-param string form, without reflection. The receiver is named x, matching
// the type-asserted local in the generated HTTPPathParams closures. f must be a
// scalar field.
func pathValueExpr(f *protogen.Field) string {
	get := "x.Get" + f.GoName + "()"
	switch f.Desc.Kind() {
	case protoreflect.StringKind:
		return get
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "strconv.FormatInt(" + get + ", 10)"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "strconv.FormatInt(int64(" + get + "), 10)"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "strconv.FormatUint(" + get + ", 10)"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "strconv.FormatUint(uint64(" + get + "), 10)"
	case protoreflect.BoolKind:
		return "strconv.FormatBool(" + get + ")"
	case protoreflect.DoubleKind:
		return "strconv.FormatFloat(" + get + ", 'f', -1, 64)"
	case protoreflect.FloatKind:
		return "strconv.FormatFloat(float64(" + get + "), 'f', -1, 64)"
	default:
		return get
	}
}

// findFieldByName matches a path param name against a message's proto fields,
// accepting both the proto name (snake_case) and the JSON name.
func findFieldByName(msg *protogen.Message, name string) *protogen.Field {
	for _, f := range msg.Fields {
		if string(f.Desc.Name()) == name || f.Desc.JSONName() == name {
			return f
		}
	}
	return nil
}

// pathBindStmt builds the assignment that copies a path value into the request
// field, converting to the field's Go type without reflection.
func pathBindStmt(goField, protoName string, f *protogen.Field) string {
	cv := "ctx.PathValue(" + strconv.Quote(protoName) + ")"
	get := "req." + goField
	switch f.Desc.Kind() {
	case protoreflect.StringKind:
		return fmt.Sprintf("%s = %s", get, cv)
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return fmt.Sprintf("%s, _ = strconv.ParseInt(%s, 10, 64)", get, cv)
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return fmt.Sprintf("if v, err := strconv.ParseInt(%s, 10, 32); err == nil { %s = int32(v) }", cv, get)
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return fmt.Sprintf("%s, _ = strconv.ParseUint(%s, 10, 64)", get, cv)
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return fmt.Sprintf("if v, err := strconv.ParseUint(%s, 10, 32); err == nil { %s = uint32(v) }", cv, get)
	case protoreflect.DoubleKind:
		return fmt.Sprintf("%s, _ = strconv.ParseFloat(%s, 64)", get, cv)
	case protoreflect.FloatKind:
		return fmt.Sprintf("if v, err := strconv.ParseFloat(%s, 32); err == nil { %s = float32(v) }", cv, get)
	case protoreflect.BoolKind:
		return fmt.Sprintf("%s, _ = strconv.ParseBool(%s)", get, cv)
	default:
		return fmt.Sprintf("%s = %s", get, cv)
	}
}

// hasPathParams reports whether any method carries an HTTP path param.
func hasPathParams(services []*serviceDesc) bool {
	for _, svc := range services {
		for _, m := range svc.Methods {
			if len(m.PathParams) > 0 {
				return true
			}
		}
	}
	return false
}

// emitHTTPPathParams generates a per-method closure map letting the replay
// middleware rebuild an HTTP path from a decoded gRPC/rpcx request. Each
// closure type-asserts the request to its concrete generated type, so no
// protobuf reflection is needed.
func emitHTTPPathParams(hg *protogen.GeneratedFile, services []*serviceDesc) {
	hg.P()
	hg.P("// HTTPPathParams returns each method's path-param values as strings so a")
	hg.P("// gRPC/rpcx call can be replayed as an HTTP curl without reflection.")
	hg.P("var HTTPPathParams = map[string]http.PathParamFunc{")
	for _, svc := range services {
		for _, m := range svc.Methods {
			if len(m.PathParams) == 0 {
				continue
			}
			recv := hg.QualifiedGoIdent(protogen.GoIdent{
				GoImportPath: m.RequestImport,
				GoName:       m.RequestType,
			})
			hg.P(strconv.Quote(svc.ServiceName+"/"+m.Name) + ": func(m any) map[string]string {")
			hg.P("\tx := m.(*" + recv + ")")
			hg.P("\treturn map[string]string{")
			for _, p := range m.PathParams {
				hg.P("\t\t" + strconv.Quote(p.ProtoName) + ": " + p.ValueExpr + ",")
			}
			hg.P("\t}")
			hg.P("},")
		}
	}
	hg.P("}")
	hg.P()
	hg.P("func init() { http.RegisterPathParams(HTTPPathParams) }")
}

// needStrconvImport reports whether any generated bind statement or replay value
// expression uses strconv.
func needStrconvImport(services []*serviceDesc) bool {
	for _, svc := range services {
		for _, m := range svc.Methods {
			for _, p := range m.PathParams {
				if strings.Contains(p.BindStmt, "strconv.") || strings.Contains(p.ValueExpr, "strconv.") {
					return true
				}
			}
		}
	}
	return false
}
